countHelper <- function() {
  cat(paste("Welcome to the manual syllable counter!",
            "You will be presented with sentences whose syllables you should count.",
            "You will also see the autogenerated count for the sentence.", 
            "To submit a syllable count, input the number and end with enter.",
            "If you want to skip counting that sentence, press enter.",
            "If you want to quit, press q, end with enter.",
            "",
            "Before we start, please enter your name (letters only):",
            sep = "\n")
  )
  
  name <- gsub(" ", ".", readline())
  usevar <- paste("manualcount_", name, sep = "")
  
  cat(paste("Do you want to download a fresh version of the sentences (y) or pick a file to continue working on (n)?"))
  choosedata <- readline()
  if (choosedata != "n") {
    load(url("https://github.com/annennenne/haikuR/raw/master/trump_beforemanualsylcount.rda"),
         envir = globalenv())
  } else {
    load(file.choose(), envir = globalenv())
  }

  
  if (!(usevar %in% names(trump))) {
    trump <- cbind(trump, usevar = NA)
  }
  
  cat(paste("Do you want to start from the first sentence, press enter.",
            "Otherwise, input the number of the sentence you wish to begin at, end with enter:",
            sep = "\n")
  )
  start <- as.numeric(readline())
  if (is.na(start)) start <- 1

  quit <- FALSE
  i <- start
  n <- nrow(trump)
  
  while (i <=n & !quit) {
    thisSentence <-   trump$sentence[i]
    theseSyllables <- trump$syllables[i]
    cat(paste(paste("Sentence ", i, ":", sep =""),
              thisSentence,
              "",
              paste("Automatic count was:", theseSyllables),
              "",
              "Input count/enter/q:",
              sep = "\n")
    )
    input <- readline()
    if (input %in% c("q", "Q")) {
      cat(paste("Ended at observation no. ", i, ". \n", sep = "")) 
      quit <- TRUE
    } 
    if (!quit) {
      trump[i, usevar] <<- as.numeric(input)
    }
    i <- i + 1
  }
  name
}

saveHelper <- function(name) {
  cat("Save dataset on disk? (y/n)")
  saveyesno <- readline()
  if (saveyesno == "y") {
    save(list = "trump", file = paste("trump_aftermanualsylcount_", name, ".rda", sep = ""))
  }
}

countSyllables <- function() {
  name <- countHelper()
  saveHelper(name)
}

countSyllables()
